root = "."
tmp_dir = "bin"

[build]
args_bin = []
bin = "./bin/main"
cmd = "make notify-templ-proxy && make build-tailwind && DEV_MODE=true go build -tags local -o ./bin/main cmd/main/main.go"
delay = 1000
exclude_dir = ["tmp", "bin"]
exclude_file = []
exclude_regex = [".*\\.txt$"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "html", "css", "templ"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
